(define (salario a b)
    (if (> a 200)
        (+ (* a b) (* b (/ 150 100)))
        (if (> a 120)
            (+ (* a b) (* (* a b) (/ 80 100)))
            (if (> a 40)
                (+ (* a b) (* (* a b) (/ 40 100)))
                (* a b)))))
(display "Salário final: ")
(display(salario 41 2))
(newline)
