(define (salario a b)
    (cond ((> a 200)
           (+ (* a b) (* b (/ 150 100))))
          ((> a 120)
           (+ (* a b) (* a b (/ 80 100))))
          ((> a 40)
           (+ (* a b) (* a b (/ 40 100))))
          (else (* a b))))

(display "Salário final: ")
(display (salario 41 2))
(newline)